# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxsim {f} {f} && open {f}')
    ```
"""

from .block import (
    C1,
    C2,
    C3,
    C3TR,
    DFL,
    SPP,
    SPPELAN,
    SPPF,
    ADown,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    ResNetLayer,
    Silence,
    BiFPN_Add2,
    BiFPN_Add3,
C2f_ParallelPolarized,
)
from .v11 import *
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .rgbd_fusion import (
    DAF,
    iAFF,
    AFF,
    MS_CAM,
    Add,
    Add2,
    GPT,
    myTransformerBlock,
    SelfAttention,
    SqueezeAndExcitation,
    Excitation,
    SqueezeAndExciteFusionAdd,
    ExciteFusionAdd,
    ResidualExciteFusion,
    ViTFlattener,
    ViTUnFlattener,
    SelfAttentionFusion,
    ResidualAttentionFusion,
    MHAttentionFusionSecond,
    MHAttentionFusionThird,
    CrossModalMultiHeadAttention,
    Concat3
)
from .mambaout import mambaout_kobe
from .mamba_yolo import *

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "Silence",
    "DAF",
    "iAFF",
    "AFF",
    "MS_CAM",
    "Add",
    "Add2",
    "GPT",
    "myTransformerBlock",
    "SelfAttention",
    "SqueezeAndExcitation",
    "Excitation",
    "SqueezeAndExciteFusionAdd",
    "ExciteFusionAdd",
    "ResidualExciteFusion",
    "ViTFlattener",
    "ViTUnFlattener",
    "SelfAttentionFusion",
    "ResidualAttentionFusion",
    "MHAttentionFusionSecond",
    "MHAttentionFusionThird",
    "CrossModalMultiHeadAttention",
    "Concat3",
    "mambaout_kobe",
    "VSSBlock_YOLO",
    "SimpleStem",
    "VisionClueMerge",
    "XSSBlock"
)
